### ISSUE TITLE
Temporary files are sometimes not deleted

### ISSUE THREAD

**Issue by kirillyu** [abstracta/jmeter-java-dsl#47] opened 2021-11-19 07:59 UTC
![image](https://user-images.githubusercontent.com/9977326/142586226-3f47a666-d923-4ce9-b617-ededeee1ac22.png)
This is not critical until they weigh a lot. In the case of using large arrays of properties, this can become a problem.

The close method does not work when the test is stopped manually, as far as I understand.

It would be nice to be able to run JMeter from the same static environment or use the bin directory of an existing JMeter on the machine. What do you think?

**Comment by rabelenda** [comment] 2021-11-19 17:54
Thank you for reporting it.

I see that when the process is interrupted the folders are not being cleaned. We will fix this in a future release.

When you say "test is stopped manually", how do you manually stop it? I guess you are interrupting it in some way, like sending quit signal to the process.

We will think about about options further and let you know. I am not sure specifying an existing JMeter installation is a good approach (versions may not match, settings might differ due to some other interventions, and tests issues may not be reproducible). I don't see a clear benefit right now on doing that. Using a unique directory (or set of directories), entirely managed by the DSL might be an option, but we still need to think further the potential implications.

**Comment by kirillyu** [comment] 2021-11-19 18:02
Yes, I interrupt it from IDEA view with stop button for example

**Comment by rabelenda** [comment] 2021-11-19 18:50
We just released a [new version](https://github.com/abstracta/jmeter-java-dsl/releases/tag/v0.33.1) which fixes this issue.

**Comment by rabelenda** [comment] 2021-11-23 15:47
I will close it, if you see any other issues please let us know.

**Closed by rabelenda** 2021-11-23 15:47 UTC
Labels: bug
