### ISSUE TITLE
NullPointerException in buildUltimateThreadGroupSchedules with threadGroup(name: "name", threads: 100, iterations: 1, child).holdFor(duration: Duration.ofMinutes(15))

### ISSUE THREAD

**Issue by polarnik** [abstracta/jmeter-java-dsl#95] opened 2022-04-19 08:00 UTC
Env:
jmeter-java-dsl.version: 0.51

Steps:

Create test with code:

```java
var testPlan =  testPlan(
    threadGroup(name: "name", threads: 100, iterations: 1,
        jsr223Sampler("subname", v -> { })
    )
    .holdFor(duration: Duration.ofMinutes(15))
);

testPlan.showInGui();
```

Result:

```
java.lang.NullPointerException
	at java.base/java.time.Duration.plus(Duration.java:690)
	at us.abstracta.jmeter.javadsl.core.threadgroups.DslDefaultThreadGroup.buildUltimateThreadGroupSchedules(DslDefaultThreadGroup.java:345)
	at us.abstracta.jmeter.javadsl.core.threadgroups.DslDefaultThreadGroup.buildUltimateThreadGroup(DslDefaultThreadGroup.java:321)
	at us.abstracta.jmeter.javadsl.core.threadgroups.DslDefaultThreadGroup.buildThreadGroup(DslDefaultThreadGroup.java:245)
	at us.abstracta.jmeter.javadsl.core.threadgroups.BaseThreadGroup.buildTestElement(BaseThreadGroup.java:58)
	at us.abstracta.jmeter.javadsl.core.testelements.BaseTestElement.buildConfiguredTestElement(BaseTestElement.java:60)
	at us.abstracta.jmeter.javadsl.core.testelements.BaseTestElement.buildTreeUnder(BaseTestElement.java:56)
	at us.abstracta.jmeter.javadsl.core.testelements.TestElementContainer.buildTreeUnder(TestElementContainer.java:47)
	at us.abstracta.jmeter.javadsl.core.BuildTreeContext.buildTreeFor(BuildTreeContext.java:78)
	at us.abstracta.jmeter.javadsl.core.BuildTreeContext.buildChild(BuildTreeContext.java:74)
	at us.abstracta.jmeter.javadsl.core.testelements.TestElementContainer.lambda$buildTreeUnder$0(TestElementContainer.java:49)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at us.abstracta.jmeter.javadsl.core.testelements.TestElementContainer.buildTreeUnder(TestElementContainer.java:48)
	at us.abstracta.jmeter.javadsl.core.BuildTreeContext.buildTreeFor(BuildTreeContext.java:78)
	at us.abstracta.jmeter.javadsl.core.DslTestPlan.saveAsJmx(DslTestPlan.java:132)
	at jmeterJavaDsl.sumulation.PerformanceTest.testPerformance2(PerformanceTest.java:119)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
```

Expected result:

Working without exceptions

Create simple thread group with 100 thread, 1 iteration and 15 minutes for rump up. And with option Delay Thread creation until needed:
<img width="766" alt="image" src="https://user-images.githubusercontent.com/7660287/163955899-d9a5b6c1-131e-4fd1-a0dc-f802b927d970.png">
(it is my goal and it is impossible now)

Or like this:
<img width="766" alt="image" src="https://user-images.githubusercontent.com/7660287/163956056-977635ce-20f8-454f-b764-ccf1ca696c0c.png">

**Comment by rabelenda** [comment] 2022-04-19 12:28
Hello, thank you for reporting this!

for sure is a bug, since no valid code should throw a NPE :). We will look into it, stay tuned for a release with the fix.

There is currently no option in the DSL for setting delayed thread creation in thread groups, but we could easily add it if you need it. Can you better describe the scenario you are trying to reproduce to understand why such option would be needed, or the reason you have behind using it?

What is that you are trying to achieve in jmeter with second setup? When you configure both number of loops and duration in jmeter, it executes threads until any of the two conditions are met, which in this case would be clearly the iterations limit. In any case, we haven't implemented such support in the DSL because we haven't seen in the past such need for configuration (stop in any of the two conditions), if you have, could you please explain when would you use it?

Regards

**Comment by rabelenda** [comment] 2022-04-21 17:45
Release [0.52.1](https://github.com/abstracta/jmeter-java-dsl/releases/tag/v0.52.1) should avoid the NPE, but changes it, in this case, with another exception since the scenario (iterations and holdFor) is not something we intend to support unless there is a clear reason for doing so (that may be the answer to one of previous questions).

**Comment by rabelenda** [comment] 2022-04-25 14:30
Closing this.

 If you have any further comments we can re open it.

**Closed by rabelenda** 2022-04-25 14:30 UTC
Labels: bug
